# Generated by Django 4.0 on 2021-12-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_activation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_book_Ticket',
            new_name='can_book_ticket',
        ),
    ]
