# Generated by Django 4.0 on 2021-12-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieshowdetail',
            old_name='movie_date',
            new_name='show_date',
        ),
    ]
